name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start Docker Compose services
        run: |
          docker-compose -f docker-compose.yml up --build -d

      - name: Run frontend tests
        run: |
          docker-compose exec edc-frontend-angular npm run test -- --watch=false

      - name: Run backend tests
        run: |
          docker-compose exec edc-backend-spring ./mvnw test

      - name: Shut down Docker Compose
        run: docker-compose -f docker-compose.yml down
